### ISSUE TITLE
Wheres the update??? 

### ISSUE THREAD

**Issue by Realoktooverr100** [ShineUA/Geometrize2GD#11]
### Select your platform

Android64

### Describe your issue

I'm waiting for the mod to update and still not a update for this mod 

I Don't know why do I have to to Mark every Extra Fields 
![IMG_20240708_075229](https://github.com/ShineUA/Geometrize2GD/assets/169684147/700c187b-8764-42b4-98d6-63ae8314e991)
For this to post

### Steps to reproduce the bug

Could you please Update the mod or you just gonna _Close_ this or Not? Or Update the mod? 

### Extra fields

- [X] I updated Geode to latest version.
- [X] I updated Geode Launcher (Android) to latest version.
- [X] I updated this mod to latest version.

**Comment by ShineUA** [comment]
WIP

**Comment by ShineUA** [comment]
Update is done now. It's just waits for validating by geode staff. Update link: https://github.com/ShineUA/Geometrize2GD/releases/tag/v1.2.1
