### ISSUE TITLE
[BUG]  on android, it says "Failed to read JSON"

### ISSUE THREAD

**Issue by sasak2** [ShineUA/Geometrize2GD#15]
### Select your platform

Android64

### Describe your issue

https://github.com/user-attachments/assets/a44299e4-ea8f-4c95-a344-487b4a192b23
Attatch videos

 Mod version 1.2.2
![Screenshot_20240801_215536_Geode](https://github.com/user-attachments/assets/03085658-e29a-409d-88fd-a5712b4ec0f9)

### Steps to reproduce the bug

When i open with android file manager and i click file, it doesn't work

### Extra fields

- [X] I updated Geode to latest version.
- [X] I updated Geode Launcher (Android) to latest version.
- [X] I updated this mod to latest version.

**Comment by ShineUA** [comment]
Try reinstalling geode loader, I had same issue before

**Comment by ShineUA** [comment]
Oops.. I meant Geode Launcher

**Comment by ShineUA** [comment]
Closing because there is no response from author of issue.
