### ISSUE TITLE
[CRASH] [PC] My game crashes after clicking "Select File" button

### ISSUE THREAD

**Issue by kkvmil** [ShineUA/Geometrize2GD#16]
### Select your platform

Windows

### Describe your issue

Upon clicking the mentioned button my game crashes. File explorer isn't beeing opened, it just goes boom :c

I have re-installed the mod and I ensured that I have the latest Geode version

### Steps to reproduce the bug

Click edit on object > JSON > Select file > game crashes

### Extra fields

- [X] I updated Geode to latest version.
- [X] I updated Geode Launcher (Android) to latest version.
- [X] I updated this mod to latest version.

**Comment by ShineUA** [comment]
Hello, it just works fine for me on Windows. Do other mods that also use filepicker work?

**Comment by kkvmil** [comment]
> Hello, it just works fine for me on Windows. Do other mods that also using filepicker work?

Wow, what a swift response. Thank you. Actually - they don't. I've tested it with custom image for something and my game crashed when trying to open file explorer. How can I fix this?

**Comment by ShineUA** [comment]
Well, it seems you need to head to geode help forum on their discord channel.

**Comment by ShineUA** [comment]
Because it looks like a geode problem

**Comment by kkvmil** [comment]
It was a megahack problem. Disabling it and restarting the game solved the issue for me. Thank you for helping me out!

**Comment by ShineUA** [comment]
You're welcome
